services:
  - type: web
    name: carbon-calculator
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python app/app.py"
    envVars:
      - key: FLASK_ENV
        value: production